title: PhenoChange
tagline: A network for monitoring the phenology of forests and savannas
description: >-
  PhenoChange uses ground-based camera systems to monitor how the vegetative
  phenology of forests and savannas is shifting under global change.
url: "https://phenochange.github.io"
baseurl: ""
repository: phenochange/phenochange.github.io
lang: en-GB
timezone: Europe/Rome
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
  - docs
plugins:
  - jekyll-seo-tag
